language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
  - "iojs"
  - "iojs-v1.0.4"
before_install:
  - npm install -g bower protractor
install:
  - npm install
  - bower install
  - webdriver-manager update --standalone
before_script:
  - gulp build-dist
  - gulp build
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - nohup bash -c "webdriver-manager start 2>&1 &"
script:
  - gulp test
